name: Build docs

on:
  push:
    branches: [ gh-pages, main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: actions/checkout@v3
    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.1
      id: install-boost
      with:
        # REQUIRED: Specify the required boost version
        # A list of supported versions can be found here: 
        # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
        boost_version: 1.80.0
    - name: Install doxygen
      run: sudo apt install -y doxygen graphviz
    - name: Install sphinx
      run: sudo apt install -y python3-sphinx python3-sphinx-book-theme python3-breathe
    - name: Install ninja
      run: sudo apt install ninja-build
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target Sphinx
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./build/docs/sphinx
        name: github-pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pages: write
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2.0.1
        with:
          # GitHub token
          token: ${{ github.token }}
          # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
          artifact_name: github-pages
          # Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)
          preview: false
